version: '3.8'

services:

  bot:
    build: ./
    ports:
      - 8000:8000
    command: sh -c "sleep 20s ; ./main"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db-dump:/var/lib/mysql
